### ISSUE TITLE
关于声明参数大小的提问

### ISSUE THREAD

**Issue by 1995hjh** [hgg111/CTest#1]
请问：
“输入三个字符串，按由小到大的顺序输出.”这个提交点中，为什么设置字符长度是100，基于什么考虑，见下图：
![image](https://user-images.githubusercontent.com/12559428/62607945-822c7b00-b931-11e9-9a46-51e56ed87f76.png)

**Comment by hgg111** [comment]
因为输入字符串的长度是未知的，所以先设一个大的数组来存放。
